apiVersion: apps/v1
kind: Deployment
metadata:
  name: people-service
  labels:
    app: people-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: people-service
  template:
    metadata:
      labels:
        app: people-service
    spec:
      containers:
      - name: people-service
        image: nityananda777/people-service:1.0
        ports:
        - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: people-service
  labels:
    app: people-service
spec:
  ports:
  - port: 8085
    protocol: TCP
  selector:
    app: people-service
  type: NodePort